### ISSUE TITLE
Support Vapor 3.0

### ISSUE THREAD

**Issue by tomisacat** [vapor/web-template#13]
There should be a `beta` branch of this template that's support Vapor 3.0 beta.

**Comment by antonyharfield** [comment]
Is anyone working on this? If not, I'm willing to have a try. :)

**Comment by 0xTim** [comment]
@antonyharfield feel free! The team are basically waiting for Leaf to be tagged and released before updating this as more than one template can be difficult to keep up to date when things are still in RC

**Comment by antonyharfield** [comment]
I had a fun 24 hours building this...
`vapor new HelloWeb --template=https://github.com/antonyharfield/vapor-web-template`

I have created a pull request, but I'm welcome to suggestions for improving it first: #14

**Comment by antonyharfield** [comment]
@0xTim Has Leaf been tagged already? If so I suspect we need to update the Package.swift before merging this?

**Comment by antonyharfield** [comment]
(Btw, just noticed there are now 2 pull requests for this issue #14 and #15.)

**Comment by 0xTim** [comment]
@antonyharfield no Leaf hasn't been tagged yet, it's still in RC

**Comment by tanner0101** [comment]
Leaf 3.0.0 is tagged and this template has now been updated for Vapor 3 👍

**Comment by antonyharfield** [comment]
Hi @tanner0101, do you want to use the improvements I made in #14? If not then I will publish it as a community web template.
